/*
 * Copyright (C) 2012 Gyver
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package com.gyver.matrixmover.gui.generator;

import com.gyver.matrixmover.effect.BoxCutOut;
import com.gyver.matrixmover.gui.component.JTextFieldSlider;
import com.gyver.matrixmover.gui.listener.interfaces.TFSListener;
import javax.swing.event.ChangeEvent;

/**
 * Configuration dialog for ColorFade Generator
 * 
 * @author Gyver
 */
public class BoxCutOutConfiguration extends javax.swing.JDialog {

    private BoxCutOut effect = null;

    /** Creates new form ColorTableDialog */
    public BoxCutOutConfiguration(java.awt.Frame parent, boolean modal, BoxCutOut effect) {
        super(parent, modal);
        this.setTitle(effect.getName().toString() + " Configuration");
        this.effect = effect;
        initComponents();

        tfsXBegin.setMinimum(0);
        tfsXBegin.setMaximum(effect.getInternalBufferXSize());
        tfsXBegin.setValue(effect.getxBegin());
        tfsXBegin.addTFSListener(new TFSListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                tfsXBeginStateChanged(e);
            }
        });

        tfsXEnd.setMinimum(0);
        tfsXEnd.setMaximum(effect.getInternalBufferXSize());
        tfsXEnd.setValue(effect.getxEnd());
        tfsXEnd.addTFSListener(new TFSListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                tfsXEndStateChanged(e);
            }
        });

        tfsYBegin.setMinimum(0);
        tfsYBegin.setMaximum(effect.getInternalBufferXSize());
        tfsYBegin.setValue(effect.getyBegin());
        tfsYBegin.addTFSListener(new TFSListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                tfsYBeginStateChanged(e);
            }
        });

        tfsYEnd.setMinimum(0);
        tfsYEnd.setMaximum(effect.getInternalBufferXSize());
        tfsYEnd.setValue(effect.getyEnd());
        tfsYEnd.addTFSListener(new TFSListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                tfsYEndStateChanged(e);
            }
        });

        
        setLocationRelativeTo(null);

    }

    private void tfsXBeginStateChanged(ChangeEvent e) {
        int value = ((JTextFieldSlider) e.getSource()).getValue();
        effect.setxBegin(value);
    }
    private void tfsXEndStateChanged(ChangeEvent e) {
        int value = ((JTextFieldSlider) e.getSource()).getValue();
        effect.setxEnd(value);
    }
    private void tfsYBeginStateChanged(ChangeEvent e) {
        int value = ((JTextFieldSlider) e.getSource()).getValue();
        effect.setyBegin(value);
    }
    private void tfsYEndStateChanged(ChangeEvent e) {
        int value = ((JTextFieldSlider) e.getSource()).getValue();
        effect.setyEnd(value);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tfsXBegin = new com.gyver.matrixmover.gui.component.JTextFieldSlider();
        tfsXEnd = new com.gyver.matrixmover.gui.component.JTextFieldSlider();
        tfsYBegin = new com.gyver.matrixmover.gui.component.JTextFieldSlider();
        tfsYEnd = new com.gyver.matrixmover.gui.component.JTextFieldSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bSaveExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tfsXBegin.setMaximum(6000);
        tfsXBegin.setMinimum(0);
        tfsXBegin.setValue(120);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        getContentPane().add(tfsXBegin, gridBagConstraints);

        tfsXEnd.setMaximum(6000);
        tfsXEnd.setMinimum(0);
        tfsXEnd.setValue(120);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        getContentPane().add(tfsXEnd, gridBagConstraints);

        tfsYBegin.setMaximum(6000);
        tfsYBegin.setMinimum(0);
        tfsYBegin.setValue(120);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        getContentPane().add(tfsYBegin, gridBagConstraints);

        tfsYEnd.setMaximum(6000);
        tfsYEnd.setMinimum(0);
        tfsYEnd.setValue(120);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 10);
        getContentPane().add(tfsYEnd, gridBagConstraints);

        jLabel1.setText("X Begin:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("X End");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Y Begin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Y End");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 5);
        getContentPane().add(jLabel4, gridBagConstraints);

        bSaveExit.setText("Save + Exit");
        bSaveExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSaveExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 10, 10);
        getContentPane().add(bSaveExit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSaveExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSaveExitActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSaveExitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bSaveExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private com.gyver.matrixmover.gui.component.JTextFieldSlider tfsXBegin;
    private com.gyver.matrixmover.gui.component.JTextFieldSlider tfsXEnd;
    private com.gyver.matrixmover.gui.component.JTextFieldSlider tfsYBegin;
    private com.gyver.matrixmover.gui.component.JTextFieldSlider tfsYEnd;
    // End of variables declaration//GEN-END:variables
}
