/*
 * Copyright (C) 2012 Gyver
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Frame.java
 *
 * Created on 17.01.2012, 09:58:43
 */
package com.gyver.matrixmover.gui;

import com.gyver.matrixmover.core.Controller;
import com.gyver.matrixmover.core.MatrixData;
import com.gyver.matrixmover.core.VisualSetup;
import com.gyver.matrixmover.effect.Effect.EffectName;
import com.gyver.matrixmover.generator.enums.GeneratorName;
import com.gyver.matrixmover.mixer.Mixer.MixerName;
import com.gyver.matrixmover.properties.PropertiesHelper;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Gyver
 */
public class Frame extends javax.swing.JFrame {

    private PropertiesHelper ph = null;
    private MatrixData md = null;
    private static Frame instance = new Frame();

    /** Creates new form Frame */
    private Frame() {
    }

    public static Frame getFrameInstance() {
        return instance;
    }

    public void initFrame(PropertiesHelper ph, Controller cont) {
        this.ph = ph;
        this.md = cont.getMatrixData();

        initComponents();
        effectPanelLeft.setSide(Controller.LEFT_SIDE);
        effectPanelRight.setSide(Controller.RIGHT_SIDE);

        generatorSetupLeft.setSide(Controller.LEFT_SIDE);
        generatorSetupRight.setSide(Controller.RIGHT_SIDE);

        effectPanelLeft.getLedScreen().init(ph, md);
        effectPanelRight.getLedScreen().init(ph, md);
        getMasterPanel().getLedScreen().init(ph, md);
        cont.setLedScreens(effectPanelLeft.getLedScreen(), effectPanelRight.getLedScreen(), getMasterPanel().getLedScreen());

        setUpComboBoxes();
    }
    
    public void centerWindow() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
          frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
          frameSize.width = screenSize.width;
        }
        this.setLocation((screenSize.width - frameSize.width) / 2,
                       (screenSize.height - frameSize.height) / 2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        masterSettings1 = new com.gyver.matrixmover.gui.MasterSettings();
        effectPanelLeft = new com.gyver.matrixmover.gui.GeneratorPanel();
        effectPanelRight = new com.gyver.matrixmover.gui.GeneratorPanel();
        masterPanel = new com.gyver.matrixmover.gui.MasterPanel();
        logoPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        generatorSetupLeft = new com.gyver.matrixmover.gui.GeneratorSetup();
        generatorSetupRight = new com.gyver.matrixmover.gui.GeneratorSetup();
        masterSettings2 = new com.gyver.matrixmover.gui.MasterSettings();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MatrixMover");
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("FrameMatrixMover"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        effectPanelLeft.setMinimumSize(new java.awt.Dimension(420, 300));
        effectPanelLeft.setPreferredSize(new java.awt.Dimension(420, 300));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(effectPanelLeft, gridBagConstraints);

        effectPanelRight.setMinimumSize(new java.awt.Dimension(420, 300));
        effectPanelRight.setPreferredSize(new java.awt.Dimension(420, 300));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(effectPanelRight, gridBagConstraints);

        masterPanel.setMinimumSize(new java.awt.Dimension(300, 350));
        masterPanel.setPreferredSize(new java.awt.Dimension(300, 350));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(masterPanel, gridBagConstraints);

        logoPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        logoPanel.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(logoPanel, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        jPanel1.add(generatorSetupLeft, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        jPanel1.add(generatorSetupRight, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(masterSettings2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        effectPanelLeft.recomputeLedPixelSize();
        effectPanelRight.recomputeLedPixelSize();
        getMasterPanel().recomputeLedPixelSize();
    }//GEN-LAST:event_formComponentResized

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Controller.getControllerInstance().saveScenes();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.gyver.matrixmover.gui.GeneratorPanel effectPanelLeft;
    private com.gyver.matrixmover.gui.GeneratorPanel effectPanelRight;
    private com.gyver.matrixmover.gui.GeneratorSetup generatorSetupLeft;
    private com.gyver.matrixmover.gui.GeneratorSetup generatorSetupRight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel logoPanel;
    private com.gyver.matrixmover.gui.MasterPanel masterPanel;
    private com.gyver.matrixmover.gui.MasterSettings masterSettings1;
    private com.gyver.matrixmover.gui.MasterSettings masterSettings2;
    // End of variables declaration//GEN-END:variables

    private void setUpComboBoxes() {

        generatorSetupLeft.setGeneratorListToComboBoxes(GeneratorName.values());
        generatorSetupRight.setGeneratorListToComboBoxes(GeneratorName.values());

        generatorSetupLeft.setEffectListToComboBoxes(EffectName.values());
        generatorSetupRight.setEffectListToComboBoxes(EffectName.values());

        generatorSetupLeft.setMixerListToComboBoxes(MixerName.values());
        generatorSetupRight.setMixerListToComboBoxes(MixerName.values());
    }

    public void setComboBoxesForChangedScene(int side, VisualSetup newActiveVisualSetup) {

        if (side == Controller.LEFT_SIDE) {
            setComboBoxes(generatorSetupLeft, newActiveVisualSetup);
        } else if (side == Controller.RIGHT_SIDE) {
            setComboBoxes(generatorSetupRight, newActiveVisualSetup);
        }
    }

    private void setComboBoxes(GeneratorSetup generatorSetup, VisualSetup newActiveVisualSetup) {
        //remove all from actionlistener when setting a new scene
        //else scene is marked as changed, due to actionlistener fired!
        generatorSetup.removeAllFromActionListener();
        
        generatorSetup.getCbGenerator1().setSelectedItem(newActiveVisualSetup.getGenerator1().getName());                
        generatorSetup.getCbGenerator2().setSelectedItem(newActiveVisualSetup.getGenerator2().getName());                
        generatorSetup.getCbEffect1().setSelectedItem(newActiveVisualSetup.getEffect1().getName());
        generatorSetup.getCbEffect2().setSelectedItem(newActiveVisualSetup.getEffect2().getName());
        generatorSetup.getCbMixer().setSelectedItem(newActiveVisualSetup.getMixer().getName());
        
        generatorSetup.getIntensitySlider1().setValue(newActiveVisualSetup.getGenerator1Intensity());
        generatorSetup.getIntensitySlider2().setValue(newActiveVisualSetup.getGenerator2Intensity());
        
        generatorSetup.addAllToActionListener();
        
    }

    public GeneratorPanel getLeftGeneratorPanel() {
        return this.effectPanelLeft;
    }

    public GeneratorPanel getRightGeneratorPanel() {
        return this.effectPanelRight;
    }

    public GeneratorSetup getLeftGeneratorSetup() {
        return this.generatorSetupLeft;
    }

    public GeneratorSetup getRightGeneratorSetup() {
        return this.generatorSetupRight;
    }

    public void setAudioLevel(int[] level) {
        this.masterSettings1.setAudioLevel(level);
    }

    public void showWarning(String string) {
        JOptionPane.showMessageDialog(this, string, "Warning", JOptionPane.WARNING_MESSAGE);
    }

    /**
     * @return the masterPanel
     */
    public com.gyver.matrixmover.gui.MasterPanel getMasterPanel() {
        return masterPanel;
    }
   
}
